- name: Run GitHub Super Linter ðŸš€

        uses: github/super-linter@main

        env:

          VALIDATE_ALL_CODEBASE: true

          LINTER_RULES_PATH: /

          VALIDATE_CLANG_FORMAT: false

          VALIDATE_JAVASCRIPT_STANDARD: false

          VALIDATE_GOOGLE_JAVA_FORMAT: false

          VALIDATE_PYTHON_FLAKE8: false

          VALIDATE_GITLEAKS: false # for secrets detection

          VALIDATE_JSON: false

          VALIDATE_JSCPD: false # for copy and paste detection

          DEFAULT_BRANCH: main

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
